package com.Entity;
// default package
// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cinema generated by hbm2java
 */
@Entity
@Table(name = "cinema")
public class Cinema  {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cinemaid", unique = true, nullable = false)
	Integer cinemaid;

	@Column(name = "name")
	String name;

	@Column(name = "address")
	String  address;
	
	@OneToMany(mappedBy = "cinema")
	List<Room> room;

	@OneToMany(mappedBy = "cinema")
	List<Employee> employee;

	public Cinema() {
		super();
	}

<<<<<<< HEAD
	public Integer getCinemaid() {
		return cinemaid;
=======
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cinemaid", unique = true, nullable = false)
	public Integer getCinemaId() {
		return this.cinemaId;
>>>>>>> 6d6c8bc42570335d28a4f29b6d1dbf5bb431bb14
	}

	public void setCinemaid(Integer cinemaid) {
		this.cinemaid = cinemaid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public List<Room> getRoom() {
		return room;
	}

	public void setRoom(List<Room> room) {
		this.room = room;
	}

<<<<<<< HEAD
	public List<Employee> getEmployee() {
		return employee;
=======
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cinemaId")
	public Set<Employee> getEmployees() {
		return this.employees;
>>>>>>> 6d6c8bc42570335d28a4f29b6d1dbf5bb431bb14
	}

	public void setEmployee(List<Employee> employee) {
		this.employee = employee;
	}

}
