package com.Entity;
// default package
// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee")
public class Employee  {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employeeid", unique = true, nullable = false)
	Integer employeeid;
	
    @ManyToOne
    @JsonIgnore
    @JoinColumn(name = "cinemaid")
	private Cinema cinemaId;
	
	@Column(name = "name")
	String name;

	@Column(name = "password")
	String password;

	@Column(name = "role")
	int role;

	@Column(name = "email")
	String email;

	@Column(name = "phone")
	String  phone;

	@Column(name = "address")
	String address;

	@Column(name = "birthday")
	Date birthday;

	@Column(name = "idcard")
	String idCard;

	@Column(name = "status")
	Integer status;
	
	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "cinemaid")
	Cinema cinema;

	@OneToMany(mappedBy = "employee")
	List<Showtimes> showtimes;

	public Employee() {
		super();
	}

	public Integer getEmployeeid() {
		return employeeid;
	}

	public void setEmployeeid(Integer employeeid) {
		this.employeeid = employeeid;
	}

	public Cinema getCinema() {
		return cinema;
	}

	public void setCinemaId(Cinema cinemaId) {
		this.cinemaId = cinemaId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getRole() {
		return role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public List<Showtimes> getShowtimes() {
		return showtimes;
	}

	public void setShowtimes(List<Showtimes> showtimes) {
		this.showtimes = showtimes;
	}
	
	

}
