package com.Entity;
// default package
// Generated Oct 11, 2020, 8:25:38 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FoodBillDetail generated by hbm2java
 */
@Entity
@Table(name = "FoodBillDetail")
public class FoodBillDetail {

	private Integer foodBillDetail;
	private Food food;
	private Ticket ticket;
	private Integer quantity;
	private Double total;

	public FoodBillDetail() {
	}

	public FoodBillDetail(Food food, Ticket ticket, Integer quantity, Double total) {
		this.food = food;
		this.ticket = ticket;
		this.quantity = quantity;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "foodBillDetail", unique = true, nullable = false)
	public Integer getFoodBillDetail() {
		return this.foodBillDetail;
	}

	public void setFoodBillDetail(Integer foodBillDetail) {
		this.foodBillDetail = foodBillDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "foodId")
	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ticketId")
	public Ticket getTicket() {
		return this.ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "total", precision = 53, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

}
