package com.Entity;
// default package
// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food")
public class Food  {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "foodid", unique = true, nullable = false)
	Integer foodId;
	
	@Column(name = "name")
	String name;

	@Column(name = "price")
	Float price;

	@Column(name = "status")
	Integer status;

	@JsonIgnore
	@OneToMany(mappedBy = "food")
	List<FoodBillDetail> foodBillDetail;

	public Food() {
		super();
	}

	public Integer getFoodId() {
		return foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public List<FoodBillDetail> getFoodBillDetail() {
		return foodBillDetail;
	}

	public void setFoodBillDetail(List<FoodBillDetail> foodBillDetail) {
		this.foodBillDetail = foodBillDetail;
	}
	
	

}
