package com.Entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * GenreMovie generated by hbm2java
 */
@Entity
@Table(name = "genremovie")
public class GenreMovie{

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "genreid", unique = true, nullable = false)
	private Integer genreId;

	@Column(name = "name")
	private String name;

	@JsonIgnore
	@OneToMany(mappedBy = "movie")
	private List<MovieGenreDetail> movieGenreDetail;

	public GenreMovie() {
	}

	public Integer getGenreId() {
		return genreId;
	}

	public void setGenreId(Integer genreId) {
		this.genreId = genreId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<MovieGenreDetail> getMovieGenreDetail() {
		return movieGenreDetail;
	}

	public void setMovieGenreDetail(List<MovieGenreDetail> movieGenreDetail) {
		this.movieGenreDetail = movieGenreDetail;
	}

}
