package com.Entity;
// default package

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * GenreMovie generated by hbm2java
 */
@Entity
@Table(name = "GenreMovie")
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "genreId")
public class GenreMovie {

	private Integer genreId;
	private String name;
//	@JsonIgnore
	private Set<MovieGenreDetail> movieGenreDetails = new HashSet<MovieGenreDetail>(0);

	public GenreMovie() {
	}

	public GenreMovie(String name, Set<MovieGenreDetail> movieGenreDetails) {
		this.name = name;
//		this.movieGenreDetails = movieGenreDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "genreId", unique = true, nullable = false)
	public Integer getGenreId() {
		return this.genreId;
	}

	public void setGenreId(Integer genreId) {
		this.genreId = genreId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genreMovie")
	public Set<MovieGenreDetail> getMovieGenreDetails() {
		return this.movieGenreDetails;
	}

	public void setMovieGenreDetails(Set<MovieGenreDetail> movieGenreDetails) {
		this.movieGenreDetails = movieGenreDetails;
	}

}
