package com.Entity;
// default package
// Generated Oct 11, 2020, 8:25:38 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie")
public class Movie{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "movieid", unique = true, nullable = false)
	private Integer movieId;
	
	@Column(name = "moviename")
	private String movieName;
	
	@Column(name = "duration")
	private Integer duration;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "thumbnail")
	private String thumbnail;
	
	@Column(name = "actors")
	private String actors;
	
	@Column(name = "director")
	private String director;
	
	@Column(name = "agelimit")
	private Integer agelimit;
	
	@Column(name = "status")
	private Integer status;
	
	@JsonIgnore
	@OneToMany(mappedBy = "movie")
	private List<MovieGenreDetail> movieGenreDetail;
	
	@JsonIgnore
	@OneToMany(mappedBy = "movie")
	List<Showtimes> showtimes;

	public Movie() {
	}

	public Integer getMovieId() {
		return movieId;
	}

	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

	public String getMovieName() {
		return movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	public Integer getDuration() {
		return duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getThumbnail() {
		return thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	public String getActors() {
		return actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public Integer getAgeLimit() {
		return agelimit;
	}

	public void setAgeLimit(Integer ageLimit) {
		this.agelimit = ageLimit;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public List<MovieGenreDetail> getMovieGenreDetail() {
		return movieGenreDetail;
	}

	public void setMovieGenreDetail(List<MovieGenreDetail> movieGenreDetail) {
		this.movieGenreDetail = movieGenreDetail;
	}

}
