package com.Entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MovieGenreDetail generated by hbm2java
 */
@Entity
@Table(name = "moviegenredetail")
public class MovieGenreDetail  {

	private Integer movieGenreDetailId;
	private GenreMovie genreMovie;
	private Movie movie;

	public MovieGenreDetail() {
	}

	public MovieGenreDetail(GenreMovie genreMovie, Movie movie) {
		this.genreMovie = genreMovie;
		this.movie = movie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "moviegenredetailid", unique = true, nullable = false)
	public Integer getMovieGenreDetailId() {
		return this.movieGenreDetailId;
	}

	public void setMovieGenreDetailId(Integer movieGenreDetailId) {
		this.movieGenreDetailId = movieGenreDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genreid")
	public GenreMovie getGenreMovie() {
		return this.genreMovie;
	}

	public void setGenreMovie(GenreMovie genreMovie) {
		this.genreMovie = genreMovie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movieid")
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

}
