package com.Entity;
// default package
// Generated Oct 11, 2020, 8:25:38 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "Movie")
public class Movie  {

	private Integer movieId;
	private String movieName;
	private Integer duration;
	private String description;
	private String thumbnail;
	private String actors;
	private String director;
	private Integer ageLimit;
	private Integer status;
	private Set<Showtimes> showtimeses = new HashSet<Showtimes>(0);
	private Set<MovieGenreDetail> movieGenreDetails = new HashSet<MovieGenreDetail>(0);

	public Movie() {
	}

	public Movie(String movieName, Integer duration, String description, String thumbnail,
			String actors, String director, Integer ageLimit, Integer status, Set<Showtimes> showtimeses,
			Set<MovieGenreDetail> movieGenreDetails) {
		this.movieName = movieName;
		this.duration = duration;
		this.description = description;
		this.thumbnail = thumbnail;
		this.actors = actors;
		this.director = director;
		this.ageLimit = ageLimit;
		this.status = status;
		this.showtimeses = showtimeses;
		this.movieGenreDetails = movieGenreDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "movieid", unique = true, nullable = false)
	public Integer getMovieId() {
		return this.movieId;
	}

	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

	@Column(name = "moviename")
	public Serializable getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "thumbnail")
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@Column(name = "actors")
	public Serializable getActors() {
		return this.actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	@Column(name = "director")
	public Serializable getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(name = "agelimit")
	public Integer getAgeLimit() {
		return this.ageLimit;
	}

	public void setAgeLimit(Integer ageLimit) {
		this.ageLimit = ageLimit;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<Showtimes> getShowtimeses() {
		return this.showtimeses;
	}

	public void setShowtimeses(Set<Showtimes> showtimeses) {
		this.showtimeses = showtimeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<MovieGenreDetail> getMovieGenreDetails() {
		return this.movieGenreDetails;
	}

	public void setMovieGenreDetails(Set<MovieGenreDetail> movieGenreDetails) {
		this.movieGenreDetails = movieGenreDetails;
	}

}
