package com.Entity;
// default package
// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room")
public class Room {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "roomid", unique = true, nullable = false)
	Integer roomId;
	
	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "cinemaId")
	Cinema cinema;

	@Column(name = "roomname")
	Integer roomName;

	@Column(name = "seatamount")
	Integer seatAmount;

	@OneToMany(mappedBy = "room")
	List<Showtimes> showtimes;

	@OneToMany(mappedBy = "room")
	List<Seat> seat;

	@Column(name = "roomid", unique = true, nullable = false)
	public Integer getRoomId() {
		return roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public Cinema getCinema() {
		return cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	public Integer getRoomName() {
		return roomName;
	}

	public void setRoomName(Integer roomName) {
		this.roomName = roomName;
	}

	public Integer getSeatAmount() {
		return seatAmount;
	}

	public void setSeatAmount(Integer seatAmount) {
		this.seatAmount = seatAmount;
	}

	public List<Showtimes> getShowtimes() {
		return showtimes;
	}

	public void setShowtimes(List<Showtimes> showtimes) {
		this.showtimes = showtimes;
	}

	public List<Seat> getSeat() {
		return seat;
	}

	public void setSeat(List<Seat> seat) {
		this.seat = seat;
	}
	
	

}
