package com.Entity;
// default package
// Generated Oct 11, 2020, 8:25:38 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name = "Seat")
public class Seat  {

	private Integer seatId;
	private Room room;
	private String seatName;
	private Set<TicketDetail> ticketDetails = new HashSet<TicketDetail>(0);

	public Seat() {
	}

	public Seat(Room room, String seatName, Set<TicketDetail> ticketDetails) {
		this.room = room;
		this.seatName = seatName;
		this.ticketDetails = ticketDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "seatId", unique = true, nullable = false)
	public Integer getSeatId() {
		return this.seatId;
	}

	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomId")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "seatName")
	public Serializable getSeatName() {
		return this.seatName;
	}

	public void setSeatName(String seatName) {
		this.seatName = seatName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seat")
	public Set<TicketDetail> getTicketDetails() {
		return this.ticketDetails;
	}

	public void setTicketDetails(Set<TicketDetail> ticketDetails) {
		this.ticketDetails = ticketDetails;
	}

}
