package com.Entity;

// default package
// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SeatStatus generated by hbm2java
 */
@Entity
@Table(name = "seatstatus")
public class SeatStatus {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "seatstatusid", unique = true, nullable = false)
	Integer seatStatusId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seatid")
	Seat seat;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "showtimeid")
	Showtimes showtimes;
	
	@Column(name = "status")
	Boolean status;

}
