package com.Entity;
// default package
// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Showtimes generated by hbm2java
 */
@Entity
@Table(name = "showtimes")
public class Showtimes {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "showtimeid", unique = true, nullable = false)
	Integer showtimeId;

	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "employeeid")
	Employee employee;

	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "movieid")
	Movie movie;

	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "periodid")
	Period period;

	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "roomid")
	Room room;

	@Column(name = "date")
	Date date;

	@Column(name = "status")
	Integer status;

	@OneToMany(mappedBy = "showtimes")
	List<SeatStatus> seatStatus;

	public Showtimes() {
		
	}
	
	public Integer getShowtimeId() {
		return showtimeId;
	}

	public void setShowtimeId(Integer showtimeId) {
		this.showtimeId = showtimeId;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Movie getMovie() {
		return movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public Period getPeriod() {
		return period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	public Room getRoom() {
		return room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public List<SeatStatus> getSeatStatus() {
		return seatStatus;
	}

	public void setSeatStatus(List<SeatStatus> seatStatus) {
		this.seatStatus = seatStatus;
	}
	
	
}
