package com.Entity;
// default package
// Generated Oct 11, 2020, 8:25:38 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TicketDetail generated by hbm2java
 */
@Entity
@Table(name = "TicketDetail")
public class TicketDetail  {

	private Integer ticketDetailId;
	private Seat seat;
	private Ticket ticket;
	private Boolean seatStatus;

	public TicketDetail() {
	}

	public TicketDetail(Seat seat, Ticket ticket, Boolean seatStatus) {
		this.seat = seat;
		this.ticket = ticket;
		this.seatStatus = seatStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticketdetailid", unique = true, nullable = false)
	public Integer getTicketDetailId() {
		return this.ticketDetailId;
	}

	public void setTicketDetailId(Integer ticketDetailId) {
		this.ticketDetailId = ticketDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seatid")
	public Seat getSeat() {
		return this.seat;
	}

	public void setSeat(Seat seat) {
		this.seat = seat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ticketid")
	public Ticket getTicket() {
		return this.ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}

	@Column(name = "seatstatus")
	public Boolean getSeatStatus() {
		return this.seatStatus;
	}

	public void setSeatStatus(Boolean seatStatus) {
		this.seatStatus = seatStatus;
	}

}
