package com.Entity;
// default package
// Generated Oct 11, 2020, 8:25:38 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "Ticket")
public class Ticket  {

	private Integer ticketId;
	private Member member;
	private Showtimes showtimes;
	private Integer periodId;
	private Integer roomId;
	private Integer cinemaId;
	private Integer ticketQuantity;
	private Double ticketPriceAmount;
	private Integer ticketCodeId;
	private String code;
	private Double total;
	private Set<TicketDetail> ticketDetails = new HashSet<TicketDetail>(0);
	private Set<FoodBillDetail> foodBillDetails = new HashSet<FoodBillDetail>(0);

	public Ticket() {
	}

	public Ticket(Member member, Showtimes showtimes, Integer periodId, Integer roomId, Integer cinemaId,
			Integer ticketQuantity, Double ticketPriceAmount, Integer ticketCodeId, String code, Double total,
			Set<TicketDetail> ticketDetails, Set<FoodBillDetail> foodBillDetails) {
		this.member = member;
		this.showtimes = showtimes;
		this.periodId = periodId;
		this.roomId = roomId;
		this.cinemaId = cinemaId;
		this.ticketQuantity = ticketQuantity;
		this.ticketPriceAmount = ticketPriceAmount;
		this.ticketCodeId = ticketCodeId;
		this.code = code;
		this.total = total;
		this.ticketDetails = ticketDetails;
		this.foodBillDetails = foodBillDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticketId", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "memberId")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "showTimeId")
	public Showtimes getShowtimes() {
		return this.showtimes;
	}

	public void setShowtimes(Showtimes showtimes) {
		this.showtimes = showtimes;
	}

	@Column(name = "periodId")
	public Integer getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(Integer periodId) {
		this.periodId = periodId;
	}

	@Column(name = "roomId")
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@Column(name = "cinemaId")
	public Integer getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Integer cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "ticketQuantity")
	public Integer getTicketQuantity() {
		return this.ticketQuantity;
	}

	public void setTicketQuantity(Integer ticketQuantity) {
		this.ticketQuantity = ticketQuantity;
	}

	@Column(name = "ticketPriceAmount", precision = 53, scale = 0)
	public Double getTicketPriceAmount() {
		return this.ticketPriceAmount;
	}

	public void setTicketPriceAmount(Double ticketPriceAmount) {
		this.ticketPriceAmount = ticketPriceAmount;
	}

	@Column(name = "ticketCodeId")
	public Integer getTicketCodeId() {
		return this.ticketCodeId;
	}

	public void setTicketCodeId(Integer ticketCodeId) {
		this.ticketCodeId = ticketCodeId;
	}

	@Column(name = "code", length = 1)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "total", precision = 53, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket")
	public Set<TicketDetail> getTicketDetails() {
		return this.ticketDetails;
	}

	public void setTicketDetails(Set<TicketDetail> ticketDetails) {
		this.ticketDetails = ticketDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket")
	public Set<FoodBillDetail> getFoodBillDetails() {
		return this.foodBillDetails;
	}

	public void setFoodBillDetails(Set<FoodBillDetail> foodBillDetails) {
		this.foodBillDetails = foodBillDetails;
	}

}
