package com.Entity;
// default package

// Generated Oct 13, 2020, 8:28:21 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket")
public class Ticket {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticketid", unique = true, nullable = false)
	Integer ticketId;

	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "memberid")
	Member member;

	@Column(name = "ticketquantity")
	Integer ticketQuantity;

	@Column(name = "ticketpriceamount")
	Float ticketPriceAmount;

	@Column(name = "code")
	String code;

	@Column(name = "total")
	Float total;

	@OneToMany(mappedBy = "ticket")
	List<TicketDetail> ticketDetail;

	@OneToMany(mappedBy = "ticket")
	List<FoodBillDetail> foodBillDetail;

	@ManyToOne
	@JsonIgnore
	@JoinColumn(name = "showtimeid")
	Showtimes showtimes;

	public Ticket() {

	}

	public Integer getTicketId() {
		return ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Integer getTicketQuantity() {
		return ticketQuantity;
	}

	public void setTicketQuantity(Integer ticketQuantity) {
		this.ticketQuantity = ticketQuantity;
	}

	public Float getTicketPriceAmount() {
		return ticketPriceAmount;
	}

	public void setTicketPriceAmount(Float ticketPriceAmount) {
		this.ticketPriceAmount = ticketPriceAmount;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Float getTotal() {
		return total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public List<TicketDetail> getTicketDetail() {
		return ticketDetail;
	}

	public void setTicketDetail(List<TicketDetail> ticketDetail) {
		this.ticketDetail = ticketDetail;
	}

	public List<FoodBillDetail> getFoodBillDetail() {
		return foodBillDetail;
	}

	public void setFoodBillDetail(List<FoodBillDetail> foodBillDetail) {
		this.foodBillDetail = foodBillDetail;
	}

	public Showtimes getShowtimes() {
		return showtimes;
	}

	public void setShowtimes(Showtimes showtimes) {
		this.showtimes = showtimes;
	}

}
